[package]
name = "json_reader"
version = "0.1.0"
authors = ["Antonio Masotti"]
license = "MIT"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
